// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;

namespace SurveyUP.Models
{
    public partial class N3mikosContext
    {

        [DbFunction("vts_fnGetFolderRootCount", "dbo")]
        public static int? vts_fnGetFolderRootCount()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }
    }
}
