// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SurveyUP.Tables
{
    public partial class VtsTbUserAnswerType
    {
        public int UserId { get; set; }
        public short AnswerTypeId { get; set; }

        public virtual VtsTbAnswerType AnswerType { get; set; }
    }
}