// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SurveyUP.Tables
{
    public partial class VtsTbVoterAnswers
    {
        public int VoterId { get; set; }
        public int AnswerId { get; set; }
        public int SectionNumber { get; set; }
        public string AnswerText { get; set; }

        public virtual VtsTbAnswer Answer { get; set; }
        public virtual VtsTbVoter Voter { get; set; }
    }
}