// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
#nullable disable

namespace SurveyUP.Tables
{
    public partial class VtsTbQuestion
    {
        public VtsTbQuestion()
        {
            VtsTbAnswer = new HashSet<VtsTbAnswer>();
        }
        [Display(Name = "Id pytania")]
        public int QuestionId { get; set; }
        [Display(Name = "Id ankiety")]
        public int? SurveyId { get; set; }
        public int? ColumnsNumber { get; set; }
        [Display(Name = "Tekst pytania")]
        public string QuestionText { get; set; }
        [Display(Name = "Pozycja pytania")]
        public int? DisplayOrder { get; set; }
        public int? PageNumber { get; set; }
        [Display(Name = "Tekst pomocniczy")]
        public string HelpText { get; set; }
        public string Alias { get; set; }
        [Display(Name = "Szablon pytań")]
        public int? QuestionGroupId { get; set; }
        [Display(Name = "Pokaż tekst pomocniczy")]
        public bool ShowHelpText { get; set; }

        [Display(Name = "Rodzaj pytania")]
        public virtual VtsTbSurvey Survey { get; set; }
        public virtual ICollection<VtsTbAnswer> VtsTbAnswer { get; set; }
        [Display(Name = "Rodzaj pytania")]
        public virtual VtsTbQuestionSelectionMode SelectionMode { get; set; }
    }
}