// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
#nullable disable

namespace SurveyUP.Tables
{
    public partial class VtsTbVoter
    {
        public VtsTbVoter()
        {
            VtsTbVoterAnswers = new HashSet<VtsTbVoterAnswers>();
        }

        public int VoterId { get; set; }
        public string Uid { get; set; }
        [Display(Name = "Id ankiety")]
        public int? SurveyId { get; set; }
        public string ContextUserName { get; set; }
        [Display(Name = "Data oddania głosu")]
        public DateTime? VoteDate { get; set; }
        [Display(Name = "Data rozpoczęcia ankiety")]
        public DateTime? StartDate { get; set; }
        [Display(Name = "Adres IP głosującego")]
        public string Ipsource { get; set; }
        [Display(Name = "Potwierdzony")]
        public bool? Validated { get; set; }

        public virtual ICollection<VtsTbVoterAnswers> VtsTbVoterAnswers { get; set; }
    }
}