// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SurveyUP.Tables
{
    public partial class VtsTbAnswer
    {
        public VtsTbAnswer()
        {
            VtsTbVoterAnswers = new HashSet<VtsTbVoterAnswers>();
        }
        [Display(Name = "Id Odpowiedzi")]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int AnswerId { get; set; }

        [Display(Name = "Pytanie")]
        public int QuestionId { get; set; }
        [Display(Name = "Typ Odpowiedzi")]
        public short? AnswerTypeId { get; set; }
        [Display(Name = "Odpowiedź")]
        public string AnswerText { get; set; }
        [Display(Name = "Wybrana odpowiedź")]
        public int? DisplayOrder { get; set; }
        [Display(Name = "Podpowiedź")]
        public string DefaultText { get; set; }


        [Display(Name = "Typ pytania")]
        public virtual VtsTbAnswerType AnswerType { get; set; }
        public virtual VtsTbQuestion Question { get; set; }
        public virtual ICollection<VtsTbVoterAnswers> VtsTbVoterAnswers { get; set; }
    }
}