// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace SurveyUP.Tables
{
    public partial class VtsTbQuestionSelectionMode
    {
        public VtsTbQuestionSelectionMode()
        {
            VtsTbQuestion = new HashSet<VtsTbQuestion>();
        }

        public byte QuestionSelectionModeId { get; set; }
        [Display(Name = "Opis")]
        public string Description { get; set; }
        public string TypeNameSpace { get; set; }
        public string TypeAssembly { get; set; }
        public int? TypeMode { get; set; }

        public virtual ICollection<VtsTbQuestion> VtsTbQuestion { get; set; }
    }
}