// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


#nullable disable

namespace SurveyUP.Tables
{
    public partial class VtsTbAnswerType
    {
        public VtsTbAnswerType()
        {
            VtsTbAnswer = new HashSet<VtsTbAnswer>();
            VtsTbUserAnswerType = new HashSet<VtsTbUserAnswerType>();
        }
     
        public short AnswerTypeId { get; set; }
        public string Description { get; set; }

        public virtual ICollection<VtsTbAnswer> VtsTbAnswer { get; set; }
        public virtual ICollection<VtsTbUserAnswerType> VtsTbUserAnswerType { get; set; }
    }
}